const RecruitmentSettings = require("../models/RecruitmentSettings");
const Task = require("../models/Task");

const getTeamAdminId = (admin) => {
  if (!admin) return null;
  if (admin.role === "SalesStaff" && admin.reportsTo) {
    return admin.reportsTo;
  }
  return admin._id;
};

const getRecruitmentSettingsDoc = async (admin) => {
  const teamAdmin = getTeamAdminId(admin);
  if (!teamAdmin) return null;
  return RecruitmentSettings.findOne({ teamAdmin });
};

const serializeEvaluationForm = (settings, evaluationFormId) => {
  if (!settings || !evaluationFormId) return null;

  const form = (settings.evaluationForms || []).find(
    (item) => String(item?._id) === String(evaluationFormId)
  );
  if (!form) return null;

  const criteriaItems = (form.criteriaItems || [])
    .map((item) => {
      const criteria = (settings.evaluationCriteria || []).find(
        (entry) => String(entry?._id) === String(item.criteriaId)
      );
      if (!criteria) return null;
      return {
        criteriaId: String(criteria._id),
        criteriaName: criteria.criteriaName,
        criteriaType: criteria.criteriaType || "None",
        description: criteria.description || "",
        proportion: Number(item.proportion || 0),
        scores: (criteria.scores || []).map((score) => ({
          score: Number(score.score || 0),
          description: score.description || "",
        })),
      };
    })
    .filter(Boolean);

  return {
    _id: String(form._id),
    formName: form.formName,
    groupCriteria: form.groupCriteria || "None",
    jobPositionId: form.jobPositionId ? String(form.jobPositionId) : null,
    criteriaItems,
  };
};

const calculateEvaluationSummary = (evaluationFormSnapshot, submittedScores = []) => {
  const scoreMap = new Map(
    (Array.isArray(submittedScores) ? submittedScores : []).map((item) => [
      String(item.criteriaId || ""),
      Number(item.score || 0),
    ])
  );

  const criteriaScores = (evaluationFormSnapshot?.criteriaItems || []).map((item) => {
    const score = Math.max(0, Math.min(5, Number(scoreMap.get(String(item.criteriaId)) || 0)));
    return {
      criteriaId: item.criteriaId,
      criteriaName: item.criteriaName,
      criteriaType: item.criteriaType || "None",
      proportion: Number(item.proportion || 0),
      score,
      maxScore: 5,
      scoreDescription:
        (item.scores || []).find((entry) => Number(entry.score) === score)?.description || "",
    };
  });

  const totalWeight = criteriaScores.reduce((sum, item) => sum + Number(item.proportion || 0), 0);
  const weightedScore = criteriaScores.reduce((sum, item) => {
    if (!item.proportion || !item.score) return sum;
    return sum + (item.score / 5) * Number(item.proportion || 0);
  }, 0);

  return {
    criteriaScores,
    totalWeight,
    percentage: Number(weightedScore.toFixed(2)),
    totalScore: Number(weightedScore.toFixed(2)),
    maxScore: Number(totalWeight.toFixed(2)),
  };
};

const generateOnboardingTasksForApplication = async ({
  admin,
  candidateType,
  candidateId,
  agentId = null,
  jobId,
}) => {
  const settings = await getRecruitmentSettingsDoc(admin);
  const steps = [...(settings?.onboardingProcesses || [])].sort(
    (left, right) => Number(left.order || 0) - Number(right.order || 0)
  );

  if (!steps.length) {
    return [];
  }

  const generatedTasks = [];

  for (const step of steps) {
    const baseFilter = {
      workflowType: "Onboarding",
      workflowSourceId: String(jobId),
      workflowStepId: String(step._id),
      candidateType,
    };

    if (candidateType === "B2C") {
      baseFilter.candidate = candidateId;
    } else {
      baseFilter.managedCandidateId = candidateId;
      baseFilter.agent = agentId;
    }

    const existingTask = await Task.findOne(baseFilter).select("_id");
    if (existingTask) continue;

    const taskPayload = {
      title: `Onboarding Step ${step.order}: ${step.subject}`,
      description: [step.content, step.attachmentName ? `Attachment: ${step.attachmentName}` : ""]
        .filter(Boolean)
        .join("\n\n"),
      type: step.attachmentName ? "Document Upload" : "Form Fill",
      status: "Pending",
      priority: "Medium",
      dueDate: new Date(Date.now() + Math.max(1, Number(step.order || 1)) * 24 * 60 * 60 * 1000),
      candidateType,
      assignedBy: admin._id,
      relatedJob: jobId,
      workflowType: "Onboarding",
      workflowSourceId: String(jobId),
      workflowStepId: String(step._id),
      autoGenerated: true,
    };

    if (candidateType === "B2C") {
      taskPayload.candidate = candidateId;
    } else {
      taskPayload.managedCandidateId = candidateId;
      taskPayload.agent = agentId;
    }

    const task = await Task.create(taskPayload);
    generatedTasks.push(task);
  }

  return generatedTasks;
};

module.exports = {
  getTeamAdminId,
  getRecruitmentSettingsDoc,
  serializeEvaluationForm,
  calculateEvaluationSummary,
  generateOnboardingTasksForApplication,
};
